---
driver:
  name: vagrant

provisioner:
  name: chef_solo

platforms:
  - name: centos-7.2

suites:
  - name: default
    run_list:
      - recipe[crf-check_mk::client]
    attributes:
      firewall:
        allow_ssh: true
