name             'crf-check_mk'
maintainer       'Crossroads Foundation Ltd'
maintainer_email 'itdept@crossroads.org.hk'
license          'Apache 2.0'
description      'Installs/Configures Check_MK'
long_description 'Installs/Configures Check_MK'
version          '0.1.0'
issues_url       'https://github.com/crossroads/crf-check_mk/issues'
source_url       'https://github.com/crossroads/crf-check_mk'

supports 'centos'

depends 'yum-epel'
depends 'python'
depends 'apache2'
depends 'certificate'
depends 'xinetd'
