name             'crf-check_mk'
maintainer       'Crossroads Foundation Ltd'
maintainer_email 'itdept@crossroads.org.hk'
license          'Apache 2.0'
description      'Installs/Configures crf-check_mk'
long_description 'Installs/Configures crf-check_mk'
version          '0.1.0'
