name             'crf-check_mk'
maintainer       'Crossroads Foundation Ltd'
maintainer_email 'itdept@crossroads.org.hk'
license          'Apache 2.0'
description      'Installs/Configures Check_MK'
long_description 'Installs/Configures Check_MK'
version          '0.2.0'
issues_url       'https://github.com/crossroads/crf-check_mk/issues'
source_url       'https://github.com/crossroads/crf-check_mk'

supports 'centos'

depends 'yum-epel', '~> 0.6'
depends 'python'
depends 'apache2'
depends 'certificate', '~> 1.0'
depends 'firewall', '~> 2.5'
depends 'systemd', '~> 2.0'
